name: CI Workflow
on:
  issues:
    types: [opened]
  push:
  pull_request:
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Run my own composite action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@romulomf'
      - name: Output the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"